# data.yaml
train: data/single_class_dataset/train
val: data/nalia_dataset/val  # Update path to your NALIA dataset


# Number of classes
nc: 1 # This will be filled by the script below

# Class names (if available)
names: [Plankton]