train: data/multiclass_dataset/train/images  # Update path to your multiclass dataset
val: data/multiclass_dataset/val/images      # Update path to your multiclass dataset

nc: 5
names:
  0: "Tripos longipes"
  1: "Tripos fusus"
  2: "Chaetoceros"
  3: "Tripos lineatum"
  4: "Coscinodiscus"